image: cirrusci/flutter:latest

variables:
before_script:
  - flutter channel master
  - flutter upgrade

stages:
  - build

build:
  stage: build
  script:
    - flutter -v build apk --release
    - mv build/app/outputs/apk/app.apk app.apk
  artifacts:
    paths:
      - app.apk
