image: darkness4/flutter-builder:27

variables:
before_script:
  - flutter channel master
  - flutter upgrade

stages:
  - build

build:
  stage: build
  script:
    - flutter packages get
    - flutter -v build apk --release
    - mv build/app/outputs/apk/app.apk app.apk
  artifacts:
    paths:
      - app.apk
    expire_in: 1 week
