stages:
  - test
  - integration-tests
  - build
  - deploy

unit-tests:
  stage: test
  image: darkness4/flutter-builder:latest

  before_script:
    - flutter channel master
    - flutter upgrade
    - flutter packages get
    - apt update
    - apt install -y lcov

  script:
    - flutter test --coverage

  after_script:
    - genhtml -o coverage coverage/lcov.info

  artifacts:
    paths:
    - coverage/

navigation_test:
  stage: integration-tests
  image: darkness4/flutter-builder:latest

  before_script:
    - flutter channel master
    - flutter upgrade
    - flutter packages get
    - sudo apt update
    - sudo apt install -y bash
    - /bin/bash ./.ci-scripts/before_script_integration_tests.sh

  script:
    - flutter drive --target=test_driver/app.dart --driver=test_driver/navigation_test.dart --build

  after_script:
    - /bin/bash ./.ci-scripts/stop-emulator

  artifacts:
    paths:
    - test_driver/screenshots/

documentation_test:
  stage: integration-tests
  image: darkness4/flutter-builder:latest

  before_script:
    - flutter channel master
    - flutter upgrade
    - flutter packages get
    - sudo apt update
    - sudo apt install -y bash
    - /bin/bash ./.ci-scripts/before_script_integration_tests.sh

  script:
    - flutter drive --target=test_driver/app.dart --driver=test_driver/documentation_test.dart --build

  ater_script:
    - /bin/bash ./.ci-scripts/stop-emulator

authentication_test:
  stage: integration-tests
  image: darkness4/flutter-builder:latest

  before_script:
    - flutter channel master
    - flutter upgrade
    - flutter packages get
    - sudo apt update
    - sudo apt install -y bash
    - /bin/bash ./.ci-scripts/before_script_integration_tests.sh

  script:
    - flutter drive --target=test_driver/app.dart --driver=test_driver/authentication_test.dart --build

  after_script:
    - /bin/bash ./.ci-scripts/stop-emulator

news_test:
  stage: integration-tests
  image: darkness4/flutter-builder:latest

  before_script:
    - flutter channel master
    - flutter upgrade
    - flutter packages get
    - sudo apt update
    - sudo apt install -y bash
    - /bin/bash ./.ci-scripts/before_script_integration_tests.sh

  script:
    - flutter drive --target=test_driver/app.dart --driver=test_driver/news_test.dart --build

  after_script:
    - /bin/bash ./.ci-scripts/stop-emulator

reporting_test:
  stage: integration-tests
  image: darkness4/flutter-builder:latest

  before_script:
    - flutter channel master
    - flutter upgrade
    - flutter packages get
    - sudo apt update
    - sudo apt install -y bash
    - /bin/bash ./.ci-scripts/before_script_integration_tests.sh

  script:
    - flutter drive --target=test_driver/app.dart --driver=test_driver/reporting_test.dart --build

  ater_script:
    - /bin/bash ./.ci-scripts/stop-emulator

pages:
  stage: deploy
  image: ruby:latest
  dependencies:
    - unit-tests

  before_script:
    - gem install coveralls-lcov
    - "echo \"repo_token: ${COVERALLS_TOKEN}\" > .coveralls.yml"

  script:
    - coveralls-lcov ./coverage/lcov.info

  after_script:
    - mv coverage/ public/

  artifacts:
    paths:
      - public

  only:
  - master
  - develop

build-test:
  stage: test
  image: darkness4/flutter-builder:latest

  before_script:
    - flutter channel master
    - flutter upgrade
    - flutter packages get
    - apt update
    - apt install -y sed
    - echo ${RELEASE_KEYSTORE_BASE64} | base64 -d > android/app/keystore.jks
    - echo "storePassword=${KEYSTORE_PASSWORD}" > android/key.properties
    - echo "keyPassword=${KEY_PASSWORD}" >> android/key.properties
    - echo "keyAlias=${ALIAS}" >> android/key.properties
    - echo "storeFile=keystore.jks" >> android/key.properties
    - sed -iEn "s/_webhook = \"ZXhlbXBsZQ==\"/_webhook = \"${CI_WEBHOOK_KEY}\"/g" ./lib/core/constants/api_constants.dart
    - sed -iEn "s/_facebookApi = \"ZXhlbXBsZQ==\"/_facebookApi = \"${CI_FACEBOOK_KEY}\"/g" ./lib/core/constants/api_constants.dart

  script:
    - flutter build apk --target-platform android-arm --split-per-abi

  except:
  - master
  - develop
  - tests

build:
  stage: build
  image: darkness4/flutter-builder:latest
  
  before_script:
    - flutter channel master
    - flutter upgrade
    - flutter packages get
    - apt update
    - apt install -y sed
    - echo ${RELEASE_KEYSTORE_BASE64} | base64 -d > android/app/keystore.jks
    - echo "storePassword=${KEYSTORE_PASSWORD}" > android/key.properties
    - echo "keyPassword=${KEY_PASSWORD}" >> android/key.properties
    - echo "keyAlias=${ALIAS}" >> android/key.properties
    - echo "storeFile=keystore.jks" >> android/key.properties
    - sed -iEn "s/_webhook = \"ZXhlbXBsZQ==\"/_webhook = \"${CI_WEBHOOK_KEY}\"/g" ./lib/core/constants/api_constants.dart
    - sed -iEn "s/_facebookApi = \"ZXhlbXBsZQ==\"/_facebookApi = \"${CI_FACEBOOK_KEY}\"/g" ./lib/core/constants/api_constants.dart

  script:
    - flutter build apk --target-platform android-arm,android-arm64 --split-per-abi

  after_script:
    - mv build/app/outputs/apk/release/app-armeabi-v7a-release.apk minitel-toolbox-armeabi-v7a.apk
    - mv build/app/outputs/apk/release/app-arm64-v8a-release.apk minitel-toolbox-arm64-v8a.apk

  artifacts:
    paths:
      - minitel-toolbox-armeabi-v7a.apk
      - minitel-toolbox-arm64-v8a.apk
    expire_in: 1 week

  only:
    - master
    - develop
