image: darkness4/flutter-builder:latest

variables:
before_script:
  - flutter channel master
  - flutter upgrade

stages:
  - test
  - build
  - deploy

unit-tests:
  stage: test
  script:
    - apt update
    - apt install -y lcov
    - flutter packages get
    - flutter test --coverage
    - genhtml -o coverage coverage/lcov.info
  artifacts:
    paths:
    - coverage/

pages:
  stage: deploy
  dependencies:
    - unit-tests
  script:
    - pub global activate coveralls
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - "echo \"repo_token: ${COVERALLS_TOKEN}\" > .coveralls.yml"
    - coveralls ./coverage/lcov.info
    - mv coverage/ public/
  artifacts:
    paths:
      - public
  only:
  - master
  - develop

build-test:
  stage: test
  script:
    - echo ${RELEASE_KEYSTORE_BASE64} | base64 -d > android/app/keystore.jks
    - echo "storePassword=${KEYSTORE_PASSWORD}" > android/key.properties
    - echo "keyPassword=${KEY_PASSWORD}" >> android/key.properties
    - echo "keyAlias=${ALIAS}" >> android/key.properties
    - echo "storeFile=keystore.jks" >> android/key.properties
    - flutter packages get
    - flutter build apk --release
  except:
  - master
  - develop
  - tests

build:
  stage: build
  script:
    - apt install -y sed
    - echo ${RELEASE_KEYSTORE_BASE64} | base64 -d > android/app/keystore.jks
    - echo "storePassword=${KEYSTORE_PASSWORD}" > android/key.properties
    - echo "keyPassword=${KEY_PASSWORD}" >> android/key.properties
    - echo "keyAlias=${ALIAS}" >> android/key.properties
    - echo "storeFile=keystore.jks" >> android/key.properties
    - sed -iEn "s/_webhook = \"ZXhlbXBsZQ==\"/_webhook = \"${CI_WEBHOOK_KEY}\"/g" ./lib/core/constants/api_constants.dart
    - sed -iEn "s/_facebookApi = \"ZXhlbXBsZQ==\"/_facebookApi = \"${CI_FACEBOOK_KEY}\"/g" ./lib/core/constants/api_constants.dart
    - flutter packages get
    - flutter build apk --release --target-platform android-arm,android-arm64 --split-per-abi
    - mv build/app/outputs/apk/release/app-armeabi-v7a-release.apk minitel-toolbox-armeabi-v7a.apk
    - mv build/app/outputs/apk/release/app-arm64-v8a-release.apk minitel-toolbox-arm64-v8a.apk
  artifacts:
    paths:
      - minitel-toolbox-armeabi-v7a.apk
      - minitel-toolbox-arm64-v8a.apk
    expire_in: 1 week
  only:
    - master
    - develop
