image: darkness4/flutter-builder:28

variables:
before_script:
  - flutter channel master
  - flutter upgrade

stages:
  - test
  - build
  - deploy

unit-tests:
  stage: test
  script:
    - apt update
    - apt install -y lcov
    - flutter packages get
    - flutter test --coverage
    - genhtml -o coverage coverage/lcov.info
  artifacts:
    paths:
    - coverage/

pages:
  stage: deploy
  dependencies:
    - unit-tests
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
  only:
  - master
  - develop

build-test:
  stage: test
  script:
    - flutter packages get
    - flutter -v build apk --release
  except:
  - tests

build:
  stage: build
  script:
    - flutter packages get
    - flutter -v build apk --release
    - mv build/app/outputs/apk/app.apk app.apk
  artifacts:
    paths:
      - app.apk
    expire_in: 1 week
  only:
    - master
