image: darkness4/flutter-builder:28

variables:
before_script:
  - flutter channel master
  - flutter upgrade

stages:
  - test
  - build

unit-tests:
  stage: test
  script:
    - flutter packages get
    - dart test/unit_test.dart

build-test:
  stage: test
  script:
    - flutter packages get
    - flutter -v build apk --release

build:
  stage: build
  script:
    - flutter packages get
    - flutter -v build apk --release
    - mv build/app/outputs/apk/app.apk app.apk
  artifacts:
    paths:
      - app.apk
    expire_in: 1 week
  only:
    - master
