site_name: Minitel Toolbox Docs
nav:
  - Home: index.md
  - Architecture Logicielle: architecture.md
  - Détails sur les fonctionnalités: features.md
  - Tests et Déploiements: cicd-deploy.md
  - Contribuer: github-workflow.md
theme:
  name: material
  palette:
    scheme: slate
    primary: green
    accent: teal

plugins:
  - mermaid2:
      arguments:
        theme: dark

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.critic:
      mode: view
  - def_list
