name: minitel_toolbox
description: Minitel Toolbox regroupe les outils les plus utiles pour avoir un WiFi sans encombre
homepage: https://github.com/Darkness4/minitel-app
repository: https://github.com/Darkness4/minitel-app
documentation: https://github.com/Darkness4/minitel-app/wiki
issue_tracker: https://github.com/Darkness4/minitel-app/issues
author: Nguyen Marc <nguyen_marc@live.fr>
version: 2.0.3+15

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.12.13 <2.0.0'

# Use ^version only if the package are stable
# ^1.2.0 means >=1.2.0 <2.0.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  webview_flutter:
    git:
      url: git://github.com/Darkness4/plugins.git
      ref: 0183a5ec8295c9593a789d2e2e88740752d0f9c1
      path: packages/webview_flutter
  connectivity: ^0.4.8+2 # Flutter Team
  share: ^0.6.3+6 # Flutter Team
  url_launcher: ^5.4.2 # Flutter Team
  shared_preferences: ^0.5.6+2 # Flutter Team
  path_provider: ^1.6.5 # Flutter Team
  sticky_headers: ^0.1.8+1 # Flutter Community
  flutter_local_notifications: ^1.2.2 # Michael Bui
  package_info: ^0.4.0+16 # Flutter Team
  intl: ^0.16.1
  ntlm: ^1.0.2 # MrBBot
  http: ^0.12.0+4 # Dart Team
  flutter_secure_storage: ^3.3.1+1 # German Saprykin
  flutter_bloc: ^3.2.0 # bloclibrary.dev
  equatable: ^1.1.0 # felangelov@gmail.com
  get_it: ^4.0.0 # fluttercommunity.dev
  flutter_markdown: ^0.3.4
  google_fonts: ^0.3.9 # material.io
  rxdart: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  mockito: ^4.1.1
  flutter_launcher_icons: ^0.7.4
  intl_translation: ^0.17.9
  matcher: ^0.12.6
  build_runner: any

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'
  adaptive_icon_background: '#43a047'
  adaptive_icon_foreground: 'assets/icon/icon.png'

flutter:
  assets:
    - assets/img/
    - assets/icon/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
  uses-material-design: true
