name: minitel_toolbox
description: Minitel Toolbox regroupe les outils les plus utiles pour avoir un WiFi sans encombre
homepage: https://github.com/Darkness4/minitel-app
repository: https://github.com/Darkness4/minitel-app
documentation: https://github.com/Darkness4/minitel-app/wiki
issue_tracker: https://github.com/Darkness4/minitel-app/issues
author: Nguyen Marc <nguyen_marc@live.fr>
version: 2.1.4+22

environment:
  sdk: '>=2.9.0 <3.0.0'

# Use ^version only if the package are stable
# ^1.2.0 means >=1.2.0 <2.0.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  webview_flutter:
    git:
      url: git://github.com/Darkness4/plugins.git
      ref: b43407289eec8e200051e1a362ed166d0d9b1c59
      path: packages/webview_flutter
  connectivity: '>=0.4.9 <2.0.0'
  share: '>=0.6.4+3 <2.0.0'
  package_info: '>=0.4.1 <2.0.0'
  shared_preferences: '>=0.5.8 <2.0.0'
  url_launcher: ^5.5.0
  path_provider: ^1.6.11
  sticky_headers: ^0.1.8+1 # Flutter Community
  flutter_local_notifications: ^1.4.4+2 # Michael Bui
  intl: ^0.16.1
  ntlm: ^1.3.0 # MrBBot
  http: ^0.12.2 # Dart Team
  flutter_secure_storage: ^3.3.3 # German Saprykin
  freezed_annotation: ^0.11.0+1
  get_it: ^4.0.4 # fluttercommunity.dev
  flutter_markdown: ^0.4.3
  google_fonts: ^1.1.0 # material.io
  rxdart: ^0.24.1
  dartx: ^0.5.0
  injectable: ^1.0.4
  alt_http: ^0.3.0
  flutter_bloc: ^6.0.1
  bloc:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test:
  matcher:
  build_runner: ^1.10.1
  mockito: ^4.1.1
  flutter_launcher_icons: ^0.7.5
  intl_translation: ^0.17.10
  freezed: ^0.11.5
  json_serializable: ^3.4.0
  injectable_generator: ^1.0.4
  pedantic: ^1.9.0

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'
  adaptive_icon_background: '#43a047'
  adaptive_icon_foreground: 'assets/icon/icon.png'

flutter:
  assets:
    - assets/img/
    - assets/icon/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
  uses-material-design: true
