name: minitel_toolbox
description: Minitel Toolbox regroupe les outils les plus utiles pour avoir un WiFi sans encombre
homepage: https://github.com/Darkness4/minitel-app
repository: https://github.com/Darkness4/minitel-app
documentation: https://github.com/Darkness4/minitel-app/wiki
issue_tracker: https://github.com/Darkness4/minitel-app/issues
author: Nguyen Marc <nguyen_marc@live.fr>
version: 2.0.6+18

environment:
  sdk: '>=2.7.0 <3.0.0'

# Use ^version only if the package are stable
# ^1.2.0 means >=1.2.0 <2.0.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  webview_flutter:
    git:
      url: git://github.com/Darkness4/plugins.git
      ref: b43407289eec8e200051e1a362ed166d0d9b1c59
      path: packages/webview_flutter
  connectivity: '>=0.4.9 <2.0.0'
  share: '>=0.6.4+3 <2.0.0'
  package_info: '>=0.4.1 <2.0.0'
  shared_preferences: '>=0.5.8 <2.0.0'
  url_launcher: ^5.5.0
  path_provider: ^1.6.11
  sticky_headers: ^0.1.8+1 # Flutter Community
  flutter_local_notifications: ^1.4.4+2 # Michael Bui
  intl: ^0.16.1
  ntlm: ^1.2.0 # MrBBot
  http: ^0.12.1 # Dart Team
  flutter_secure_storage: ^3.3.3 # German Saprykin
  flutter_bloc: ^5.0.1 # bloclibrary.dev
  freezed_annotation: ^0.11.0
  get_it: ^4.0.2 # fluttercommunity.dev
  flutter_markdown: ^0.4.2
  google_fonts: ^1.1.0 # material.io
  rxdart: ^0.24.1
  dartx: ^0.4.2
  injectable: ^0.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  mockito: ^4.1.1
  flutter_launcher_icons: ^0.7.5
  intl_translation: ^0.17.10
  matcher: ^0.12.8
  build_runner: any
  freezed: ^0.11.2
  json_serializable: ^3.3.0
  extra_pedantic: ^1.2.0
  injectable_generator: ^0.4.1

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'
  adaptive_icon_background: '#43a047'
  adaptive_icon_foreground: 'assets/icon/icon.png'

flutter:
  assets:
    - assets/img/
    - assets/icon/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
  uses-material-design: true
