name: minitel_toolbox
description: Minitel Toolbox regroupe les outils les plus utiles pour avoir un WiFi sans encombre

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.2.0

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  connectivity: ^0.4.3+6  # Flutter Team
  dscript_exec: ^2.0.1  # Ravi Teja Gudapti
  share: ^0.6.2+1  # Flutter Team
  webfeed: ^0.4.2  # Wito Chandra
  url_launcher: ^5.1.1  # Flutter Team
  # google_maps_flutter: ^0.5.19+2  # Flutter Team
  permission_handler: ^3.2.1+1  # Baseflow
  shared_preferences: ^0.5.3+4  # Flutter Team
  webview_flutter: ^0.3.10+4  # Flutter Team
  path_provider: ^1.2.0  # Flutter Team
  sticky_headers: ^0.1.8  # Flutter Community
  flutter_local_notifications: ^0.8.0  # Michael Bui
  html: ^0.14.0+2  # Dart Team
  package_info: ^0.4.0+6  # Flutter Team
  device_info: ^0.4.0+2  # Flutter Team
  provider: ^3.0.0+1
  # font_awesome_flutter: ^8.5.0  # Brian Egan

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_launcher_icons: any

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#43a047"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/img/
    - assets/icon/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Italic.ttf
          style: italic
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
        - asset: fonts/RobotoMono-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/RobotoMono-Light.ttf
          weight: 300
        - asset: fonts/RobotoMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: fonts/RobotoMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/RobotoMono-Thin.ttf
          weight: 100
        - asset: fonts/RobotoMono-ThinItalic.ttf
          weight: 100
          style: italic
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
        - asset: fonts/NotoSans-Italic.ttf
          style: italic
        - asset: fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/NotoSans-Light.ttf
          weight: 300
        - asset: fonts/NotoSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/NotoSans-Medium.ttf
          weight: 500
        - asset: fonts/NotoSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/NotoSans-Thin.ttf
          weight: 100
        - asset: fonts/NotoSans-ThinItalic.ttf
          weight: 100
          style: italic
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
