name: minitel_toolbox
description: Minitel Toolbox regroupe les outils les plus utiles pour avoir un WiFi sans encombre
homepage: https://github.com/Darkness4/minitel-app
repository: https://github.com/Darkness4/minitel-app
documentation: https://github.com/Darkness4/minitel-app/wiki
issue_tracker: https://github.com/Darkness4/minitel-app/issues
author: Nguyen Marc <nguyen_marc@live.fr>
version: 2.3.0+26

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc:
  connectivity: ^3.0.3
  dartx: ^0.7.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_local_notifications: ^5.0.0 # Michael Bui
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.1
  flutter_secure_storage: ^4.1.0 # German Saprykin
  freezed_annotation: ^0.14.1
  get_it: ^6.0.0 # fluttercommunity.dev
  google_fonts: ^2.0.0 # material.io
  http: ^0.13.1 # Dart Team
  injectable: ^1.2.2
  intl: ^0.17.0
  ntlm: ^2.0.1 # MrBBot
  package_info: ^2.0.0
  path_provider: ^2.0.1
  rxdart: ^0.26.0
  share: ^2.0.1
  shared_preferences: ^2.0.5
  sticky_headers: ^0.2.0 # Flutter Community
  timezone:
  url_launcher: ^6.0.3
  webview_cookie_manager: ^2.0.0-nullsafety.0
  webview_flutter: ^2.0.2

dev_dependencies:
  analyzer:
  build_runner:
  # flutter_driver:
  #   sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1+1
  injectable_generator: ^1.2.2
  # intl_translation: ^0.17.10+1
  json_serializable: ^4.1.0
  matcher:
  mockito: ^5.0.3
  pedantic: ^1.11.0
  test:

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'
  adaptive_icon_background: '#43a047'
  adaptive_icon_foreground: 'assets/icon/icon.png'

flutter:
  assets:
    - assets/img/
    - assets/icon/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
  uses-material-design: true
