name: minitel_toolbox
description: Minitel Toolbox regroupe les outils les plus utiles pour avoir un WiFi sans encombre
homepage: https://github.com/Darkness4/minitel-app
repository: https://github.com/Darkness4/minitel-app
documentation: https://github.com/Darkness4/minitel-app/wiki
issue_tracker: https://github.com/Darkness4/minitel-app/issues
author: Nguyen Marc <nguyen_marc@live.fr>
version: 1.0.0

environment:
  sdk: ^2.4.0
  flutter: ^1.9.1

# Use ^version only if the package are stable
# ^1.2.0 means >=1.2.0 <2.0.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  webview_flutter:
    git: 
      url: git://github.com/Darkness4/plugins.git
      ref: 618342283949a53242ed5c31bc178086a4716d94
      path: packages/webview_flutter
  connectivity: ^0.4.4  # Flutter Team
  share: ^0.6.2+1  # Flutter Team
  url_launcher: ^5.1.2  # Flutter Team
  shared_preferences: ^0.5.3+4  # Flutter Team
  path_provider: ^1.3.0  # Flutter Team
  sticky_headers: ^0.1.8  # Flutter Community
  flutter_local_notifications: ^0.8.2+1  # Michael Bui
  package_info: ^0.4.0+6  # Flutter Team
  device_info: ^0.4.0+2  # Flutter Team
  provider: ^3.1.0  # Remi Rousselet and Flutter Team
  intl: any
  ntlm: ^1.0.2  # MrBBot
  http: ^0.12.0+2  # Dart Team

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  mockito: ^4.1.1
  extra_pedantic: ^1.0.0
  flutter_launcher_icons: 0.7.2+1

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#43a047"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter:
  assets:
    - assets/img/
    - assets/icon/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
  uses-material-design: true
