name: minitel_toolbox
description: Minitel Toolbox regroupe les outils les plus utiles pour avoir un WiFi sans encombre
homepage: https://github.com/Darkness4/minitel-app
author: Nguyen Marc <nguyen_marc@live.fr>
version: 0.5.0

environment:
  sdk: ">=2.5.0 <3.0.0"

# Use ^version only if the package are stable
# ^1.2.0 means >=1.2.0 <2.0.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  connectivity: 0.4.3+7  # Flutter Team
  dscript_exec: ^2.0.1  # Ravi Teja Gudapti
  share: 0.6.2+1  # Flutter Team
  webfeed: 0.4.2  # Wito Chandra
  url_launcher: ^5.1.2  # Flutter Team
  shared_preferences: 0.5.3+4  # Flutter Team
  webview_flutter: 0.3.13  # Flutter Team
  path_provider: ^1.2.0  # Flutter Team
  sticky_headers: 0.1.8  # Flutter Community
  flutter_local_notifications: 0.8.2  # Michael Bui
  package_info: 0.4.0+6  # Flutter Team
  device_info: 0.4.0+2  # Flutter Team
  provider: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  extra_pedantic: ^1.0.0
  flutter_launcher_icons: 0.7.2+1

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#43a047"
  adaptive_icon_foreground: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/img/
    - assets/icon/
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
