// Mocks generated by Mockito 5.0.3 from annotations
// in minitel_toolbox/test/data/repositories/login_settings_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:minitel_toolbox/data/datasources/settings/login_settings_data_source.dart'
    as _i3;
import 'package:minitel_toolbox/domain/entities/login_settings.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeLoginSettings extends _i1.Fake implements _i2.LoginSettings {}

/// A class which mocks [LoginSettingsDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDataSource extends _i1.Mock
    implements _i3.LoginSettingsDataSource {
  MockLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.LoginSettings> load() =>
      (super.noSuchMethod(Invocation.method(#load, []),
              returnValue: Future.value(_FakeLoginSettings()))
          as _i4.Future<_i2.LoginSettings>);
  @override
  _i4.Future<void> save(_i2.LoginSettings? settings) =>
      (super.noSuchMethod(Invocation.method(#save, [settings]),
          returnValue: Future.value(null),
          returnValueForMissingStub: Future.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> clear() => (super.noSuchMethod(Invocation.method(#clear, []),
      returnValue: Future.value(null),
      returnValueForMissingStub: Future.value()) as _i4.Future<void>);
}
