// Mocks generated by Mockito 5.0.3 from annotations
// in minitel_toolbox/test/data/repositories/zabbix_hosts_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:minitel_toolbox/data/datasources/zabbix/zabbix_remote_data_source.dart'
    as _i2;
import 'package:minitel_toolbox/domain/entities/zabbix/zabbix_host.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ZabbixRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSource extends _i1.Mock
    implements _i2.ZabbixRemoteDataSource {
  MockRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ZabbixHost>> fetchZabbixHosts(int? groupids) =>
      (super.noSuchMethod(Invocation.method(#fetchZabbixHosts, [groupids]),
              returnValue: Future.value(<_i4.ZabbixHost>[]))
          as _i3.Future<List<_i4.ZabbixHost>>);
}
