// Mocks generated by Mockito 5.0.3 from annotations
// in minitel_toolbox/test/data/datasources/emse/imprimante_remote_data_source_test.dart.
// Do not manually edit this file.

import 'dart:_http' as _i11;
import 'dart:async' as _i6;
import 'dart:convert' as _i9;
import 'dart:typed_data' as _i4;

import 'package:http/src/base_request.dart' as _i7;
import 'package:http/src/multipart_request.dart' as _i8;
import 'package:http/src/response.dart' as _i3;
import 'package:http/src/streamed_response.dart' as _i2;
import 'package:minitel_toolbox/core/cookies/cookie_manager.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ntlm/src/http.dart' as _i5;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

class _FakeStreamedResponse extends _i1.Fake implements _i2.StreamedResponse {}

class _FakeResponse extends _i1.Fake implements _i3.Response {}

class _FakeUint8List extends _i1.Fake implements _i4.Uint8List {}

/// A class which mocks [NTLMClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockNTLMClient extends _i1.Mock implements _i5.NTLMClient {
  MockNTLMClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get domain =>
      (super.noSuchMethod(Invocation.getter(#domain), returnValue: '')
          as String);
  @override
  set domain(String? _domain) =>
      super.noSuchMethod(Invocation.setter(#domain, _domain),
          returnValueForMissingStub: null);
  @override
  String get workstation =>
      (super.noSuchMethod(Invocation.getter(#workstation), returnValue: '')
          as String);
  @override
  set workstation(String? _workstation) =>
      super.noSuchMethod(Invocation.setter(#workstation, _workstation),
          returnValueForMissingStub: null);
  @override
  String get username =>
      (super.noSuchMethod(Invocation.getter(#username), returnValue: '')
          as String);
  @override
  set username(String? _username) =>
      super.noSuchMethod(Invocation.setter(#username, _username),
          returnValueForMissingStub: null);
  @override
  String get headerPrefix =>
      (super.noSuchMethod(Invocation.getter(#headerPrefix), returnValue: '')
          as String);
  @override
  set headerPrefix(String? _headerPrefix) =>
      super.noSuchMethod(Invocation.setter(#headerPrefix, _headerPrefix),
          returnValueForMissingStub: null);
  @override
  _i6.Future<_i2.StreamedResponse> send(_i7.BaseRequest? originalReq) =>
      (super.noSuchMethod(Invocation.method(#send, [originalReq]),
              returnValue: Future.value(_FakeStreamedResponse()))
          as _i6.Future<_i2.StreamedResponse>);
  @override
  _i6.Future<_i2.StreamedResponse> multipart(_i8.MultipartRequest? request) =>
      (super.noSuchMethod(Invocation.method(#multipart, [request]),
              returnValue: Future.value(_FakeStreamedResponse()))
          as _i6.Future<_i2.StreamedResponse>);
  @override
  _i6.Future<_i3.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future.value(_FakeResponse()))
          as _i6.Future<_i3.Response>);
  @override
  _i6.Future<_i3.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future.value(_FakeResponse()))
          as _i6.Future<_i3.Response>);
  @override
  _i6.Future<_i3.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i9.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future.value(_FakeResponse()))
          as _i6.Future<_i3.Response>);
  @override
  _i6.Future<_i3.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i9.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future.value(_FakeResponse()))
          as _i6.Future<_i3.Response>);
  @override
  _i6.Future<_i3.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i9.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future.value(_FakeResponse()))
          as _i6.Future<_i3.Response>);
  @override
  _i6.Future<_i3.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i9.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future.value(_FakeResponse()))
          as _i6.Future<_i3.Response>);
  @override
  _i6.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future.value('')) as _i6.Future<String>);
  @override
  _i6.Future<_i4.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future.value(_FakeUint8List()))
          as _i6.Future<_i4.Uint8List>);
}

/// A class which mocks [CookieManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockCookieManager extends _i1.Mock implements _i10.CookieManager {
  MockCookieManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i11.Cookie> get imprimanteCookies =>
      (super.noSuchMethod(Invocation.getter(#imprimanteCookies),
          returnValue: <_i11.Cookie>[]) as List<_i11.Cookie>);
  @override
  List<_i11.Cookie> get portailCookies =>
      (super.noSuchMethod(Invocation.getter(#portailCookies),
          returnValue: <_i11.Cookie>[]) as List<_i11.Cookie>);
}
