String latestRelease = r"""{
    "url": "https://api.github.com/repos/Darkness4/minitel-app/releases/19520136",
    "assets_url": "https://api.github.com/repos/Darkness4/minitel-app/releases/19520136/assets",
    "upload_url": "https://uploads.github.com/repos/Darkness4/minitel-app/releases/19520136/assets{?name,label}",
    "html_url": "https://github.com/Darkness4/minitel-app/releases/tag/0.5.2",
    "id": 123456789,
    "node_id": "MDc6UmVsZWFzZTE5NTIwMTM2",
    "tag_name": "0.5.2",
    "target_commitish": "master",
    "name": "Hotfix 0.5.2",
    "draft": false,
    "author": {
      "login": "Darkness4",
      "id": 18192844,
      "node_id": "MDQ6VXNlcjE4MTkyODQ0",
      "avatar_url": "https://avatars3.githubusercontent.com/u/18192844?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Darkness4",
      "html_url": "https://github.com/Darkness4",
      "followers_url": "https://api.github.com/users/Darkness4/followers",
      "following_url": "https://api.github.com/users/Darkness4/following{/other_user}",
      "gists_url": "https://api.github.com/users/Darkness4/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Darkness4/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Darkness4/subscriptions",
      "organizations_url": "https://api.github.com/users/Darkness4/orgs",
      "repos_url": "https://api.github.com/users/Darkness4/repos",
      "events_url": "https://api.github.com/users/Darkness4/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Darkness4/received_events",
      "type": "User",
      "site_admin": false
    },
    "prerelease": false,
    "created_at": "2019-08-25T19:16:20Z",
    "published_at": "2019-08-25T19:17:16Z",
    "assets": [
      {
        "url": "https://api.github.com/repos/Darkness4/minitel-app/releases/assets/14561096",
        "id": 14561096,
        "node_id": "MDEyOlJlbGVhc2VBc3NldDE0NTYxMDk2",
        "name": "minitel-toolbox-arm64-v8a.apk",
        "label": null,
        "uploader": {
          "login": "Darkness4",
          "id": 18192844,
          "node_id": "MDQ6VXNlcjE4MTkyODQ0",
          "avatar_url": "https://avatars3.githubusercontent.com/u/18192844?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Darkness4",
          "html_url": "https://github.com/Darkness4",
          "followers_url": "https://api.github.com/users/Darkness4/followers",
          "following_url": "https://api.github.com/users/Darkness4/following{/other_user}",
          "gists_url": "https://api.github.com/users/Darkness4/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Darkness4/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Darkness4/subscriptions",
          "organizations_url": "https://api.github.com/users/Darkness4/orgs",
          "repos_url": "https://api.github.com/users/Darkness4/repos",
          "events_url": "https://api.github.com/users/Darkness4/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Darkness4/received_events",
          "type": "User",
          "site_admin": false
        },
        "content_type": "application/vnd.android.package-archive",
        "state": "uploaded",
        "size": 9034801,
        "download_count": 3,
        "created_at": "2019-08-25T19:17:06Z",
        "updated_at": "2019-08-25T19:17:09Z",
        "browser_download_url": "https://github.com/Darkness4/minitel-app/releases/download/0.5.2/minitel-toolbox-arm64-v8a.apk"
      },
      {
        "url": "https://api.github.com/repos/Darkness4/minitel-app/releases/assets/14561095",
        "id": 14561095,
        "node_id": "MDEyOlJlbGVhc2VBc3NldDE0NTYxMDk1",
        "name": "minitel-toolbox-armeabi-v7a.apk",
        "label": null,
        "uploader": {
          "login": "Darkness4",
          "id": 18192844,
          "node_id": "MDQ6VXNlcjE4MTkyODQ0",
          "avatar_url": "https://avatars3.githubusercontent.com/u/18192844?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/Darkness4",
          "html_url": "https://github.com/Darkness4",
          "followers_url": "https://api.github.com/users/Darkness4/followers",
          "following_url": "https://api.github.com/users/Darkness4/following{/other_user}",
          "gists_url": "https://api.github.com/users/Darkness4/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/Darkness4/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/Darkness4/subscriptions",
          "organizations_url": "https://api.github.com/users/Darkness4/orgs",
          "repos_url": "https://api.github.com/users/Darkness4/repos",
          "events_url": "https://api.github.com/users/Darkness4/events{/privacy}",
          "received_events_url": "https://api.github.com/users/Darkness4/received_events",
          "type": "User",
          "site_admin": false
        },
        "content_type": "application/vnd.android.package-archive",
        "state": "uploaded",
        "size": 8731963,
        "download_count": 0,
        "created_at": "2019-08-25T19:17:06Z",
        "updated_at": "2019-08-25T19:17:08Z",
        "browser_download_url": "https://github.com/Darkness4/minitel-app/releases/download/0.5.2/minitel-toolbox-armeabi-v7a.apk"
      }
    ],
    "tarball_url": "https://api.github.com/repos/Darkness4/minitel-app/tarball/0.5.2",
    "zipball_url": "https://api.github.com/repos/Darkness4/minitel-app/zipball/0.5.2",
    "body": "# Hotfix 0.5.2\r\n\r\n## Changelog\r\n\r\n- Portail: Stop adding indefinitely cookies\r\n- Portail: Better cookie clearance\r\n- Gateway: French\r\n- Reporting: Validators and new fields (+ optimizations), close #69 \r\n- Diagnosis: Fix lookup wrong IP"
  }""";

String responseAllReleases = """[
  $latestRelease
]""";
