import 'package:freezed_annotation/freezed_annotation.dart';

import 'event.dart';
import 'timezone.dart';

part 'parsed_calendar.freezed.dart';

/// Section of an icalendar
enum ICalSection { None, VEVENT, VTIMEZONE, STANDARD, DAYLIGHT }

/// Parsed calendar generated by [parseCalendar]
@freezed
class ParsedCalendar with _$ParsedCalendar {
  const factory ParsedCalendar({
    required String version,
    required String prodID,
    required String calscale,
    required Timezone timezone,
    required List<Event> events,
  }) = _ParsedCalendar;
}
