on:
  push:
    branches:
      - develop

name: Develop Workflow
jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Java 8
        uses: actions/setup-java@master
        with:
          java-version: '8.x'
      - name: Flutter action
        uses: subosito/flutter-action@master
        with:
          channel: 'beta'
      - name: Upgrade flutter to beta latest
        run: |
          flutter channel beta
          flutter upgrade
          flutter --version
      - run: flutter pub get
      - run: sudo apt update
      - name: Install LCOV
        run: sudo apt install -y lcov
      - name: run test coverage
        run: |
          flutter test --coverage
          lcov -r coverage/lcov.info $(cat ./.lcovignore) -o coverage/lcov.info
          genhtml -o coverage coverage/lcov.info
      - name: Archive Coverage
        uses: actions/upload-artifact@master
        with:
          name: coverage
          path: coverage
      - name: Deploy coverage
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: develop
          BRANCH: gh-pages
          FOLDER: coverage
  integration-tests:
    name: Integration tests
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Java 8
        uses: actions/setup-java@master
        with:
          java-version: '8.x'
      - name: Flutter action
        uses: subosito/flutter-action@master
        with:
          channel: 'beta'
      - name: Upgrade flutter to beta latest
        run: |
          flutter channel beta
          flutter upgrade
          flutter --version
      - name: Inject env variables
        env:
          RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          CI_WEBHOOK_KEY: ${{ secrets.CI_WEBHOOK_KEY }}
          CI_CONSUMER_KEY: ${{ secrets.CI_CONSUMER_KEY }}
          CI_CONSUMER_SECRET: ${{ secrets.CI_CONSUMER_SECRET }}
        run: sh ./.ci-scripts/test_variables.sh
      - name: run tests
        timeout-minutes: 30
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          profile: 'pixel'
          script: /Users/runner/Library/Android/sdk/tools/bin/avdmanager list && sleep 20 && flutter doctor -v && flutter pub get && sh test_integration.sh
      - name: upload screenshot
        uses: actions/upload-artifact@master
        with:
          name: screenshots
          path: test_driver/screenshots
  apk-build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Java 8
        uses: actions/setup-java@master
        with:
          java-version: '8.x'
      - name: Flutter action
        uses: subosito/flutter-action@master
        with:
          channel: 'beta'
      - name: Upgrade flutter to beta latest
        run: |
          flutter channel beta
          flutter upgrade
          flutter --version
      - name: Inject env variables
        env:
          RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          CI_WEBHOOK_KEY: ${{ secrets.CI_WEBHOOK_KEY }}
          CI_CONSUMER_KEY: ${{ secrets.CI_CONSUMER_KEY }}
          CI_CONSUMER_SECRET: ${{ secrets.CI_CONSUMER_SECRET }}
        run: sh ./.ci-scripts/test_variables.sh
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi
      - name: Rename outputs
        run: |
          cp build/app/outputs/apk/release/app-armeabi-v7a-release.apk build/app/outputs/apk/release/toolbox-armeabi-v7a.apk
          cp build/app/outputs/apk/release/app-arm64-v8a-release.apk build/app/outputs/apk/release/toolbox-arm64-v8a.apk
          cp build/app/outputs/apk/release/app-x86_64-release.apk build/app/outputs/apk/release/toolbox-x86_64.apk
      - name: Archive APK
        uses: actions/upload-artifact@master
        with:
          name: release-apks
          path: build/app/outputs/apk/release
  aab-build:
    name: Build AAB
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Java 8
        uses: actions/setup-java@master
        with:
          java-version: '8.x'
      - name: Flutter action
        uses: subosito/flutter-action@master
        with:
          channel: 'beta'
      - name: Upgrade flutter to beta latest
        run: |
          flutter channel beta
          flutter upgrade
          flutter --version
      - name: Inject env variables
        env:
          RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          CI_WEBHOOK_KEY: ${{ secrets.CI_WEBHOOK_KEY }}
          CI_CONSUMER_KEY: ${{ secrets.CI_CONSUMER_KEY }}
          CI_CONSUMER_SECRET: ${{ secrets.CI_CONSUMER_SECRET }}
        run: sh ./.ci-scripts/test_variables.sh
      - run: flutter pub get
      - run: flutter build appbundle --release
      - name: Move and renamed outputs
        run: cp build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/toolbox.aab
      - name: Archive AAB
        uses: actions/upload-artifact@master
        with:
          name: release-aab
          path: build/app/outputs/bundle/release
  # web-build:
  #   name: Build and Deploy Web
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Setup Java 12
  #       uses: actions/setup-java@master
  #       with:
  #         java-version: '12.x'
  #     - name: Flutter action
  #       uses: subosito/flutter-action@master
  #       with:
  #         channel: 'beta'
  #     - name: Upgrade flutter to beta latest
  #       run: |
  #         flutter channel beta
  #         flutter upgrade
  #         flutter --version
  #     - run: flutter pub get
  #     - run: flutter config --enable-web
  #     - run: flutter build web --release
  #     - name: Deploy to Firebase
  #       uses: w9jds/firebase-action@master
  #       with:
  #         args: deploy --only hosting
  #       env:
  #         FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
